### PR TITLE
Use https in links in speaker detail cards

### PR DESCRIPTION
**Pull request by webknjaz**

### CODE REVIEW

**Comment by benabraham** [comment]
Why?

**Comment by webknjaz** [comment]
because raw http is bad and vulnerable to MITM attacks

**Comment by benabraham** [comment]
Oh for sure! Thanks for spotting that out.

I read just the PR name (which said use http…).

**Comment by webknjaz** [comment]
yeah... it's funny to have a typo in the description of fixing that same typo :laughing:

**Comment by benabraham** [comment]
I also checked all other links hardcoded in templates and changed them to https where possible
https://github.com/pyvec/cz.pycon.org-2019/commit/3eeea2b603c6a8b91d4b86d0e5984c1b59112bf7

Is deployed now.

**Pull request merged**
