### PR TITLE
Add duration (in minutes) for Slot model

### PR DESCRIPTION
**Pull request by frenzymadness**
Because it's blocking me from creating a programme on the web, I decided to add a simple field.

Unfortunately, I am not good enough in Django to implement also check that there is no overlap with existing slots but it can be implemented later by @mcurlej.

If this will be merged, I am able to move the program from battleplan to db tomorrow.

### CODE REVIEW

**Comment by benabraham** [comment]
why not datetime field?

**Comment by benabraham** [comment]
we agreed on datetime field #4 (same complexity as this)

**Comment by frenzymadness** [comment]
My mistake, sorry, I did it in a hurry.

**Comment by benabraham** [comment]
That's why we do PRs :)

**Comment by benabraham** [comment]
That's why we do PRs :)

**Comment by frenzymadness** [comment]
Fixed. Hopefully, it doesn't break anything else.

**Comment by benabraham** [comment]
deployed

**Comment by benabraham** [comment]
(beta too)

**Pull request merged**
