### PR TITLE
Add has_detail and in_data_track to Talks and Workshops

### PR DESCRIPTION
**Pull request by encukou**
@benabraham Not sure if this is exactly how you want it. Change it as needed or do it some other way :)

### CODE REVIEW

**Comment by starenka** [comment]
there's still `is_public` flag there, what is this `has_detail` for? every talk should have a detail. if not is not public.... i don't like having 1000 flags on a simple model. the reason is, nobody knows what it does and when it used... just my .5E

**Comment by benabraham** [comment]
@starenka 

Simple is better than complex but an app doing what needs to be done is also a good idea…

I have yet to see non-trivial code that doesn't require developers’ knowledge of business logic.

It's an option to publish a session only partially and we should add a `help_text` explaining it.

**Comment by benabraham** [comment]
But we decided to not do it this year and I added in_data_track in my branch already so I will close this. Thanks @encukou

**Comment by encukou** [comment]
Yea, it probably makes sense to add these as you need them in templates.
But as starenka says, don't overdo it :)

**Pull request closed without merging**
