### PR TITLE
Listing ready for partial publishing

### PR DESCRIPTION
**Pull request by benabraham**

### CODE REVIEW

**Comment by benabraham** [comment]
deployed

**Comment by starenka** [comment]
more_to_come = nonbackup_talks.filter(is_public=False).exists()

**Comment by benabraham** [comment]
https://github.com/pyvec/cz.pycon.org-2019/commit/89952cd97ad30fb49e94bb92cd73f5404b2d75b2

**Comment by benabraham** [comment]
deployed

**Pull request merged**
