### PR TITLE
fixes #87: incorrect workshop lengths

### LINKED ISSUE #87: Programme/workshop admin doesn't allow to save 3 hour workshop
Admin shows 2 hours (can't save 3 hours).
Because of this?

```
 LENGTH = (
        ('1h', '1 hour'),
        ('2h', '2 hours'),
        ('2h', '3 hours'),
        ('1d', 'Full day (most sprints go here!)'),
        ('xx', 'Something else! (Please leave a note in the abstract)')
 )
```

Everybody in accepted proposals has 3 hour workshop (except Caletka)

FYI @frenzymadness

### PR DESCRIPTION
**Pull request by benabraham**

### CODE REVIEW

**Comment by benabraham** [comment]
FYI @Glutexo (can't change in admin until this is merged and deployed…)

**Comment by frenzymadness** [comment]
Looks good to me. Merge/deploy at will.

**Comment by benabraham** [comment]
deployed

**Comment by benabraham** [comment]
and changed all workshops to 3 hours (not sure if they really are, but is now same as saved proposals data 🤡)

**Pull request merged**
